chain_client:
  chain_id: chain
  user_sign_key_file_path: config/user_admin.key
  crypto:
    hash: SHA256
  auth_type: public
  enable_normal_key: false
  nodes:
    - node_addr: 10.0.4.8:12301
      conn_cnt: 5
    - node_addr: 10.0.4.8:12302
      conn_cnt: 5
  rpc_client:
    max_receive_message_size: 16
    max_send_message_size: 16